apiVersion: skaffold/v4beta9
kind: Config
manifests:
  rawYaml:
    - "./02_infra/01_k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: frankjia/auth
      context: 01_auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: frankjia/client
      context: 03_client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: frankjia/tickets
      context: 05_tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
        